### PR TITLE
Master

### PR DESCRIPTION
**Pull request by GrimaldiCharts**

### CODE REVIEW

**Comment by cmgiven** [comment]
Delaware!

Very cool. Closing this PR without merging, as the only changes are the alternate data set.

**Comment by GrimaldiCharts** [comment]
I have no idea what I'm doing. Never used Github before but i love your election map site. Very well done! I cant seem to get my map to show on my webpage. It appears fine in the repository. Any clue? Thank you in advance.

 http://grimaldicharts.github.io/open-election-map/

**Comment by cmgiven** [comment]
All good! You need to create a branch called gh-pages and push it to Github. If you're working from the command line, these are the commands you'd run from your project directory:

```
git checkout -b gh-pages
git push origin gh-pages
```

The first command creates and "checks out" a new branch called gh-pages. The second pushes it to Github.

**Comment by cmgiven** [comment]
More info here: https://help.github.com/categories/github-pages-basics/

**Comment by GrimaldiCharts** [comment]
Thank you. It doesnt seem to work for me. Do you do this for a living? Any chance of me hiring you to complete? I think its mostly done but just cant get the map to load on the page.

**Comment by cmgiven** [comment]
Looks like it's working: http://grimaldicharts.github.io/open-election-map/

Note that the map is not appearing as the precinct geometries array in precinct-boundaries.json is keyed `9f4b57dd8f98d21fe9ebd00976cd581e` while the script expects it to be keyed `precincts`.

**Pull request closed without merging**
